Loading cache...done.
Loaded 2075 entries from dependency cache.
Parsing recipes...done.
Parsing of 1273 .bb files complete (1271 cached, 2 parsed). 2078 targets, 349 skipped, 0 masked, 0 errors.
WARNING: No bb files matched BBFILE_PATTERN_dti '^/home/deby/poky/meta-debian/tests/../../meta-debian/bsp/meta-ti/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.42.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-deby-linux-gnueabi"
MACHINE              = "beaglebone"
DISTRO               = "deby-tiny"
DISTRO_VERSION       = "10.0"
TUNE_FEATURES        = "arm armv7a vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            = "warrior:79a850a10a4b88a6d20d607b322542f947874323"
meta-debian          = "warrior:fda6a80e4cae9aa03f502551f35fe41beb7bb944"
meta-ti              = "master:d793618c727d5a334241699d4421dbfc539be86c"
meta-ti              = "warrior:fda6a80e4cae9aa03f502551f35fe41beb7bb944"

Initialising tasks...done.
Sstate summary: Wanted 6 Found 0 Missed 6 Current 125 (0% match, 95% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Running task 598 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_fetch)
NOTE: recipe python-setuptools-40.8.0-r0: task do_fetch: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_fetch: Succeeded
NOTE: Running task 753 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_unpack)
NOTE: Running task 754 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_prepare_recipe_sysroot)
NOTE: recipe python-setuptools-40.8.0-r0: task do_unpack: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_prepare_recipe_sysroot: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_unpack: Succeeded
NOTE: Running task 755 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_debian_unpack_extra)
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_unpack_extra: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_unpack_extra: Succeeded
NOTE: Running task 756 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_debian_patch)
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_patch: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_prepare_recipe_sysroot: Succeeded
NOTE: recipe python-setuptools-40.8.0-r0: task do_debian_patch: Succeeded
NOTE: Running task 757 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_patch)
NOTE: recipe python-setuptools-40.8.0-r0: task do_patch: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_patch: Succeeded
NOTE: Running task 758 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_configure)
NOTE: Running task 759 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_populate_lic)
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_lic: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_configure: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_lic: Succeeded
NOTE: recipe python-setuptools-40.8.0-r0: task do_configure: Succeeded
NOTE: Running task 760 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_compile)
NOTE: recipe python-setuptools-40.8.0-r0: task do_compile: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_compile: Succeeded
NOTE: Running task 761 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_install)
NOTE: recipe python-setuptools-40.8.0-r0: task do_install: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_install: Succeeded
NOTE: Running task 762 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_package)
NOTE: Running task 763 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_populate_sysroot)
NOTE: recipe python-setuptools-40.8.0-r0: task do_package: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_sysroot: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_populate_sysroot: Succeeded
NOTE: recipe python-setuptools-40.8.0-r0: task do_package: Succeeded
NOTE: Running task 764 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_packagedata)
NOTE: recipe python-setuptools-40.8.0-r0: task do_packagedata: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_packagedata: Succeeded
NOTE: Running task 765 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_package_write_deb)
NOTE: Running task 766 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_package_qa)
NOTE: recipe python-setuptools-40.8.0-r0: task do_package_qa: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_package_write_deb: Started
NOTE: recipe python-setuptools-40.8.0-r0: task do_package_qa: Succeeded
NOTE: recipe python-setuptools-40.8.0-r0: task do_package_write_deb: Succeeded
NOTE: Running noexec task 767 of 767 (/home/deby/poky/meta-debian/recipes-debian/python/python-setuptools_debian.bb:do_build)
NOTE: Tasks Summary: Attempted 767 tasks of which 751 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.
